version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]

  backend:
    image: ghcr.io/emperorsarath/jobportal-backend:latest
    restart: unless-stopped
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  frontend:
    image: ghcr.io/emperorsarath/jobportal-frontend:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080

volumes:
  esdata:
